
spring:

#  h2:
#    console:
#      enabled: true
#  #  SQL statements will be printed in the console.
#  jpa:
#    show-sql: true
#  #  Hibernate will drop and recreate the database schema on each application startup.
#    hibernate:
#      ddl-auto: create
#  # In memory means this will persist data until the application is running If the application starts,
#  #  then a database clears all the data
#  datasource:
#    url: jdbc:h2:mem:test


#  #  This is the setup for postgres database
#
#  datasource:
#    # jdbc means a protocol using which can connect to a database
#    # postgresql means database name or database type
#    # //localhost:5432/user This is a database url, and here user is a database name
#    url: jdbc:postgresql://localhost:5432/user
#    username: eshopdb
#    password: aakash@1707
#
#  jpa:
#    database: POSTGRESQL
#    #  SQL statements will be printed in the console.
#    show-sql: true
#    #  Hibernate will drop and recreate the database schema on each application startup. This is used for schema management
#    hibernate:
#      ddl-auto: update
#    # Whenever spring-boot interacts with a database, it creates a query
#    database-platform: org.hibernate.dialect.PostgreSQLDialect

#  This is the setup for mongodb database
  data:
    mongodb:
#      This is a local mongodb database
      uri: ${MONGO_URI}

#      This is url of a remote database ( mongodb atlas )
#      uri: mongodb+srv://prajapatiaakash364:bZ7vdsjmMFVpOVAE@user-data.61hjt8l.mongodb.net/?retryWrites=true&w=majority&appName=user-data
      database: ${DB_NAME}

server:
  port: 8082