#spring.application.name=config-demo
spring:
  application:
    name: configdemo

#  here setup for a spring cloud config client
#  This marked is as optional, if not able to fetch from remote location then access from local environment variable (yml or properties file)
  config:
    import: optional:configserver:http://localhost:8888
#   If I pass default profile from program argument, environment in intellij IDE, then we don't
#   need to pass here profiles.active=dev
  profiles:
    active: dev

# This is a default active profile
build:
##  This is the way to get dynamically id here if we set ID=9999 like in intellij IDE
#  id: ${ID}
  id: 122
#  version: ${VERSION}
  version: 2.2.2
#  name: ${NAME}
  name: "Default-Build"


#  This is how we set environment variable from intellij IDE
#  BUILD_ID=444444;BUILD_NAME=NAME_TEST;BUILD_VERSION=1.8.0

# This is how we get dynamic value with ${} sign
# ID=444444; NAME=NAME_TEST; VERSION=1.8.0