#spring.application.name=config-demo
build:
  id: 101
  version: 1.2.3
  name: "Native Dev-Production-Build 123 After Implement Bus Refresh"
  type: "Native Development Build"

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  # Here define actuator
management:
  endpoints:
    web:
      exposure:
        include : "*"